In [275]:
import numpy as np
n = np.array([1,2,3,4,5])
b = np.array([True, False, True, False, True])

n[b]

array([1, 3, 5])

In [276]:
n>2

array([False, False,  True,  True,  True])

In [277]:
n[n>2]

array([3, 4, 5])

In [278]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,7,8,9])

a[(a<b) | (b%2==0)]

array([2, 4, 5, 6])

# LABO 1

Construir arrays a partir de una lista simple y una lista anidada usando tipos de datos numéricos distintos para cada una

In [279]:
import numpy as np

In [280]:
n = np.array([1,2,3,4,5,6], dtype=np.int16)
n

array([1, 2, 3, 4, 5, 6], dtype=int16)

In [281]:
n = np.array([[1,2,3],[4,5,6]], dtype=np.int8)
n

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

Construir una matriz de 4x5 a partir de: 1) listas anidadas y 2) números aleatorios

# LABO 3

1. Crear un array a partir del archivo “numeros.csv”
2. ¿Cuántas filas y columnas tiene?
3. Realizar las siguientes estadísticas para todas las columnas:
promedio, desviación standard, mínimo y máximo
4. ¿Qué columna tiene mayor dispersión?
5. ¿Qué columna abarca un rango de números más amplio?

In [282]:
# 1:
f = np.genfromtxt("numeros.csv", dtype=None)
f

array([[ 4.813,  3.892, 15.295, 14.966, -2.629, 10.321],
       [ 6.281,  1.71 , 15.081, 11.82 , -5.391,  9.507],
       [ 5.923,  4.602, 14.809,  8.604, -2.694,  9.48 ],
       ...,
       [ 4.408,  2.114, 15.326,  8.805, -3.355, 11.287],
       [ 6.437,  2.542, 15.378, 13.038, -4.922, 11.014],
       [ 6.665,  0.87 , 15.143, 17.716, -3.466,  8.881]])

In [283]:
# 2:
f.shape

(50000, 6)

In [284]:
# 3:
print(f.mean(axis = 0))
print(f.std(axis = 0))
print(f.min(axis = 0))
print(f.max(axis = 0))

[ 5.9997414   2.00692114 15.0025543  12.03065986 -3.00791112  9.99568554]
[1.00023883 2.00229762 0.4993279  3.00265157 2.496453   1.50167353]
[  1.639  -6.068  12.767   0.015 -13.386   4.398]
[10.409 11.162 17.09  23.678  7.668 16.516]


In [285]:
np.max(f.std(axis = 0))

3.0026515742264963

In [286]:
np.max(f.cumsum(axis = 0))

750127.7149999978

In [287]:
(f.max(axis=0) - f.min(axis=0).argmax())

array([ 8.409,  9.162, 15.09 , 21.678,  5.668, 14.516])

# LABO 4

1. Crear un vector de diez números al azar.
2. Calcular la norma del vector usando:

    a. producto escalar.

    b. función a tal efecto.

3. Crear una matriz de 2x3 y multiplicarla por su traspuesta.
4. Multiplicar la matriz identidad por un vector columna.

In [311]:
# 1:
n = np.random.randint(0,9,(10,))

In [312]:
print(np.linalg.norm(n))
print(np.sqrt(n.dot(n)))

12.922847983320086
12.922847983320086


In [313]:
n2 = np.random.randint(0,9,(2,3))
n2@n2.T

array([[88, 58],
       [58, 45]])

In [318]:
np.identity(3)@np.random.randint(0,9,(3))

array([2., 7., 8.])