In [95]:
import numpy as np
n = np.array([1,2,3,4,5])
b = np.array([True, False, True, False, True])

n[b]

array([1, 3, 5])

In [96]:
n>2

array([False, False,  True,  True,  True])

In [97]:
n[n>2]

array([3, 4, 5])

In [98]:
a = np.array([1,2,3,4,5,6])
b = np.array([1,2,3,7,8,9])

a[(a<b) | (b%2==0)]

array([2, 4, 5, 6])

# LABO 1

Construir arrays a partir de una lista simple y una lista anidada usando tipos de datos numéricos distintos para cada una

In [99]:
import numpy as np

In [100]:
n = np.array([1,2,3,4,5,6], dtype=np.int16)
n

array([1, 2, 3, 4, 5, 6], dtype=int16)

In [101]:
n = np.array([[1,2,3],[4,5,6]], dtype=np.int8)
n

array([[1, 2, 3],
       [4, 5, 6]], dtype=int8)

Construir una matriz de 4x5 a partir de: 1) listas anidadas y 2) números aleatorios

In [102]:
np.array([[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]])

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [103]:
np.random.randint(0,10, size=(4,5))

array([[8, 2, 5, 2, 7],
       [0, 3, 8, 9, 0],
       [7, 7, 3, 7, 3],
       [4, 6, 8, 4, 8]])

Construir un array lineal de 36 elementos. Cambiar
el shape para que tenga:

1. 3 filas y 12 columnas

2. 4 columnas

3. dimensión 4

In [104]:
n = np.arange(36)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [105]:
n.reshape(3,12)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [106]:
n.reshape((-1,4))
n.reshape((2,2,3,3))

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

1. Dado un array de enteros de shape (4, 6) seleccionar:

a. El primer elemento de la primer fila

b. La segunda fila

c. La cuarta columna

d. Las columnas de índice par

e. Los elementos mayores a 7 (u otra condición a elección)

2. Al mismo array asignarle el valor 100 al último elemento
de la última fila.

3. Asignarle 0 a la quinta columna.

In [152]:
n = np.random.randint(10,size=(4,6))
n

array([[6, 5, 7, 3, 3, 7],
       [9, 7, 7, 9, 7, 7],
       [7, 6, 2, 6, 3, 2],
       [6, 5, 0, 9, 0, 5]])

In [153]:
n[0,0]

6

In [154]:
n[1, :]

array([9, 7, 7, 9, 7, 7])

In [155]:
n[:, 3]

array([3, 9, 6, 9])

In [156]:
n[:, ::2]

array([[6, 7, 3],
       [9, 7, 7],
       [7, 2, 3],
       [6, 0, 0]])

In [157]:
n[n>7]

array([9, 9, 9])

In [158]:
n[-1,-1] = 100
n

array([[  6,   5,   7,   3,   3,   7],
       [  9,   7,   7,   9,   7,   7],
       [  7,   6,   2,   6,   3,   2],
       [  6,   5,   0,   9,   0, 100]])

In [162]:
n[:, 4] = 0
n

array([[  6,   5,   7,   3,   0,   7],
       [  9,   7,   7,   9,   0,   7],
       [  7,   6,   2,   6,   0,   2],
       [  6,   5,   0,   9,   0, 100]])

# LABO 2

1. Calcular los cubos de los primeros 15 naturales.

2. Sumar la matriz identidad a una matriz llena de unos.

3. Hacer una función que calcule grados Fahrenheit a partir
de un array con grados Celsius.

4. Hacer una función que tome dos arrays (peso y altura) y
calcule el índice de masa corporal.

5. Crear una matriz de 4x5 llena de ceros. Sumar 10 a la
tercera columna usando broadcasting.

6. Encontrar los elementos de un array que son menores a
los logaritmos al cuadrado de los elementos de otro array.

In [2]:
import numpy as np
#1
n = np.arange(15)
n**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744], dtype=int32)

In [184]:
#2
np.identity(3) + np.ones((3,3))

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [4]:
#3
def f(c):
    return c*1.8+32
f(np.arange(10))

array([32. , 33.8, 35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2])

In [16]:
#4
def imc(w, h):
    return w/h**2

In [18]:
#5
n = np.zeros((4, 5))
n + np.array([0,0,10,0,0])

array([[ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.]])

In [19]:
#6
A = np.random.randint(1,20,(10,10))
B = np.random.randint(1,20,(10,10))

A[A < np.log(B)**2]

array([7, 3, 4, 7, 2, 2, 6, 3, 1, 3, 6, 4, 2, 7, 8, 3, 4, 4, 6, 4, 5, 3,
       3, 4, 4, 5, 1, 2, 1])

# LABO 3

1. Crear un array a partir del archivo “numeros.csv”
2. ¿Cuántas filas y columnas tiene?
3. Realizar las siguientes estadísticas para todas las columnas:
promedio, desviación standard, mínimo y máximo
4. ¿Qué columna tiene mayor dispersión?
5. ¿Qué columna abarca un rango de números más amplio?

In [186]:
# 1:
f = np.genfromtxt("numeros.csv", dtype=None)
f

array([[ 4.813,  3.892, 15.295, 14.966, -2.629, 10.321],
       [ 6.281,  1.71 , 15.081, 11.82 , -5.391,  9.507],
       [ 5.923,  4.602, 14.809,  8.604, -2.694,  9.48 ],
       ...,
       [ 4.408,  2.114, 15.326,  8.805, -3.355, 11.287],
       [ 6.437,  2.542, 15.378, 13.038, -4.922, 11.014],
       [ 6.665,  0.87 , 15.143, 17.716, -3.466,  8.881]])

In [187]:
# 2:
f.shape

(50000, 6)

In [188]:
# 3:
print(f.mean(axis = 0))
print(f.std(axis = 0))
print(f.min(axis = 0))
print(f.max(axis = 0))

[ 5.9997414   2.00692114 15.0025543  12.03065986 -3.00791112  9.99568554]
[1.00023883 2.00229762 0.4993279  3.00265157 2.496453   1.50167353]
[  1.639  -6.068  12.767   0.015 -13.386   4.398]
[10.409 11.162 17.09  23.678  7.668 16.516]


In [189]:
#4
np.max(f.std(axis = 0))

3.0026515742264963

In [190]:
np.max(f.cumsum(axis = 0))

750127.7149999978

In [191]:
(f.max(axis=0) - f.min(axis=0).argmax())

array([ 8.409,  9.162, 15.09 , 21.678,  5.668, 14.516])

# LABO 4

1. Crear un vector de diez números al azar.
2. Calcular la norma del vector usando:

    a. producto escalar.

    b. función a tal efecto.

3. Crear una matriz de 2x3 y multiplicarla por su traspuesta.
4. Multiplicar la matriz identidad por un vector columna.

In [192]:
# 1:
n = np.random.randint(0,9,(10,))

In [193]:
#2
print(np.linalg.norm(n))
print(np.sqrt(n.dot(n)))

17.916472867168917
17.916472867168917


In [194]:
#3
n2 = np.random.randint(0,9,(2,3))
n2@n2.T

array([[  8,  24],
       [ 24, 105]])

In [195]:
#4
np.identity(3)@np.random.randint(0,9,(3))

array([4., 7., 5.])